export const ErrorCode = {
  // Authentication Errors (AUTH_*)
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",

  // User Errors (USER_*)
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_INVALID_ID: "USER_INVALID_ID",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_DELETE_FAILED: "USER_DELETE_FAILED",

  // Transaction Errors (TRANSACTION_*)
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  TRANSACTION_INVALID_AMOUNT: "TRANSACTION_INVALID_AMOUNT",
  TRANSACTION_INVALID_DATE: "TRANSACTION_INVALID_DATE",
  TRANSACTION_CREATE_FAILED: "TRANSACTION_CREATE_FAILED",
  TRANSACTION_UPDATE_FAILED: "TRANSACTION_UPDATE_FAILED",
  TRANSACTION_DELETE_FAILED: "TRANSACTION_DELETE_FAILED",

  // Validation Errors (VALIDATION_*)
  VALIDATION_ERROR: "VALIDATION_ERROR",
  VALIDATION_REQUIRED_FIELD: "VALIDATION_REQUIRED_FIELD",
  VALIDATION_INVALID_EMAIL: "VALIDATION_INVALID_EMAIL",
  VALIDATION_INVALID_PASSWORD: "VALIDATION_INVALID_PASSWORD",
  VALIDATION_PASSWORD_TOO_SHORT: "VALIDATION_PASSWORD_TOO_SHORT",
  VALIDATION_INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",

  // Database Errors (DB_*)
  DB_CONNECTION_ERROR: "DB_CONNECTION_ERROR",
  DB_QUERY_ERROR: "DB_QUERY_ERROR",
  DB_TRANSACTION_ERROR: "DB_TRANSACTION_ERROR",
  DB_CONSTRAINT_VIOLATION: "DB_CONSTRAINT_VIOLATION",

  // Server Errors (SERVER_*)
  SERVER_ERROR: "SERVER_ERROR",
  SERVER_NOT_IMPLEMENTED: "SERVER_NOT_IMPLEMENTED",
  SERVER_SERVICE_UNAVAILABLE: "SERVER_SERVICE_UNAVAILABLE",

  // Rate Limit Errors (RATE_LIMIT_*)
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Resource Errors (RESOURCE_*)
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
